import type { Article, ProductRecommendation } from '@/types/content'

export const mockArticles: Article[] = [
  {
    id: 'a1',
    slug: 'checklist-realista-para-recibir-a-un-cachorro',
    title: 'Checklist realista para recibir a un cachorro en casa',
    excerpt: 'Lo esencial para preparar espacio, rutinas y primeras compras sin agobiarte ni gastar de mas.',
    category: 'perros',
    readTime: '6 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-03-12',
    updatedAt: '2026-03-18',
    featured: true,
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80',
    tags: ['cachorros', 'rutinas', 'hogar'],
    heroNote: 'Una llegada tranquila cambia por completo la adaptacion de tu cachorro durante las primeras semanas.',
    takeaways: [
      'Prioriza orden, descanso y horarios estables antes que comprar demasiadas cosas.',
      'Haz una primera visita veterinaria temprana para tener una hoja de ruta clara.',
      'Reduce estimulos y presenta cada espacio de la casa de forma progresiva.',
    ],
    ctaLabel: 'Ver esenciales para el dia a dia',
    seoTitle: 'Checklist para recibir a un cachorro en casa | Vida Mascotera',
    seoDescription: 'Guia practica para preparar tu hogar, definir rutinas y acompanar a tu cachorro con calma desde el primer dia.',
    body: [
      {
        title: 'Empieza por el ambiente, no por las compras',
        paragraphs: [
          'Un cachorro no necesita una casa perfecta, necesita un entorno predecible. Define una zona de descanso, un lugar fijo para comer y una rutina simple para sus primeros dias.',
          'Cuando todo cambia al mismo tiempo, la adaptacion se vuelve mas dificil. Menos ruido, menos visitas y mas calma suelen dar mejores resultados que una bienvenida llena de estimulos.',
        ],
      },
      {
        title: 'Crea una rutina amable desde el primer dia',
        paragraphs: [
          'Los horarios de comida, sueno, paseo y juego ayudan a que el cachorro entienda que esperar. Eso reduce ansiedad, accidentes en casa y despertares mas caoticos.',
          'No hace falta hacerlo perfecto. Lo importante es repetir una estructura simple para que poco a poco empiece a sentirse seguro.',
        ],
      },
      {
        title: 'Compra lo que vas a usar de verdad',
        paragraphs: [
          'Cama lavable, comedero facil de limpiar, arnes comodo, placas de identificacion y juguetes resistentes suelen ser una mejor inversion que accesorios improvisados.',
          'Antes de comprar por impulso, piensa si ese producto mejora bienestar, seguridad o convivencia diaria. Si no cumple una de esas tres funciones, puede esperar.',
        ],
      },
    ],
  },
  {
    id: 'a2',
    slug: 'como-enriquecer-un-departamento-para-un-gato-indoor',
    title: 'Como enriquecer un departamento para un gato indoor',
    excerpt: 'Ideas concretas para sumar altura, juego y descanso sin saturar el espacio ni romper la armonia de tu hogar.',
    category: 'gatos',
    readTime: '5 min',
    author: 'Marta Cifuentes',
    publishedAt: '2026-03-09',
    updatedAt: '2026-03-15',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=80',
    tags: ['indoor', 'hogar', 'bienestar'],
    heroNote: 'Un gato que puede observar, esconderse, rascar y jugar a diario suele vivir mas tranquilo y mas estimulado.',
    takeaways: [
      'La verticalidad importa tanto como el espacio horizontal.',
      'Es mejor tener pocos recursos bien ubicados que muchos elementos dispersos.',
      'El juego corto y frecuente suele funcionar mejor que una sesion larga ocasional.',
    ],
    ctaLabel: 'Explorar ideas para espacios felinos',
    seoTitle: 'Como enriquecer un departamento para un gato indoor | Vida Mascotera',
    seoDescription: 'Descubre como crear un espacio seguro, estimulante y armonioso para un gato de interior.',
    body: [
      {
        title: 'La altura es parte del bienestar felino',
        paragraphs: [
          'Los gatos de interior necesitan puntos altos para observar el entorno, descansar y sentirse seguros. Estantes, rascadores altos o muebles junto a una ventana pueden cambiar mucho su rutina.',
          'No se trata de llenar la casa de estructuras. Basta con crear uno o dos recorridos bien pensados que les permitan subir, parar y mirar con calma.',
        ],
      },
      {
        title: 'Escondites y zonas de descanso reducen el estres',
        paragraphs: [
          'Una caja, una cama tipo cueva o una manta en un rincon tranquilo pueden ser suficientes para que tu gato tenga un refugio propio.',
          'Cuando los gatos sienten que siempre tienen donde retirarse, suelen mostrarse mas confiados y mas abiertos al juego y al contacto.',
        ],
      },
      {
        title: 'Jugar tambien es una forma de cuidar',
        paragraphs: [
          'El juego estimula, previene aburrimiento y ayuda a canalizar energia. Varitas, pelotas ligeras y pequenos circuitos de busqueda suelen dar buen resultado.',
          'Reserva unos minutos dos o tres veces al dia. Esa frecuencia suele ser mas efectiva que esperar al fin de semana para compensar.',
        ],
      },
    ],
  },
  {
    id: 'a3',
    slug: 'pienso-humedo-o-mixto-como-elegir-segun-tu-mascota',
    title: 'Pienso, humedo o mixto: como elegir segun tu mascota',
    excerpt: 'Una guia sencilla para entender ventajas, limites y cuando conviene combinar formatos sin complicarte.',
    category: 'alimentacion',
    readTime: '7 min',
    author: 'Dra. Ana Reategui',
    publishedAt: '2026-03-04',
    updatedAt: '2026-03-10',
    image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?auto=format&fit=crop&w=1200&q=80',
    tags: ['nutricion', 'comparativa', 'guia'],
    heroNote: 'No existe un unico formato ideal para todos: la mejor eleccion depende de hidratacion, rutina, presupuesto y tolerancia digestiva.',
    takeaways: [
      'Observa energia, digestion, hidratacion y apetito, no solo el precio del alimento.',
      'El formato mixto puede ser util cuando quieres equilibrio entre practicidad y palatabilidad.',
      'Cualquier cambio debe hacerse de forma gradual durante varios dias.',
    ],
    ctaLabel: 'Ver seleccion para la hora de comer',
    seoTitle: 'Pienso, humedo o mixto: como elegir mejor | Vida Mascotera',
    seoDescription: 'Comparativa clara entre alimento seco, humedo y mixto para decidir segun las necesidades reales de tu mascota.',
    body: [
      {
        title: 'El alimento seco destaca por practicidad',
        paragraphs: [
          'Suele ser comodo de almacenar, facil de racionar y mas estable una vez abierto. Para muchas familias esto facilita mantener horarios regulares.',
          'Aun asi, conviene vigilar que tu mascota beba suficiente agua y revisar siempre la calidad de ingredientes y la tolerancia digestiva.',
        ],
      },
      {
        title: 'El formato humedo suma hidratacion y atractivo',
        paragraphs: [
          'Es una opcion interesante para mascotas con poco interes por el agua, etapas sensibles o apetito irregular.',
          'Como suele tener otra relacion costo-porcion, puede funcionar mejor como alimento principal en ciertos casos o como apoyo dentro de una pauta combinada.',
        ],
      },
      {
        title: 'El esquema mixto puede ser el punto medio',
        paragraphs: [
          'Combinar ambos formatos permite sumar hidratacion sin renunciar a la practicidad. Tambien ayuda a hacer las comidas mas variadas para algunos perros y gatos.',
          'La clave esta en mantener porciones claras y evitar improvisar cantidades, porque un sistema mixto mal ajustado puede llevar a excesos sin darte cuenta.',
        ],
      },
    ],
  },
  {
    id: 'a4',
    slug: 'cuidados-basicos-de-piel-oidos-y-patas-despues-del-paseo',
    title: 'Cuidados basicos de piel, oidos y patas despues del paseo',
    excerpt: 'Una rutina breve para detectar molestias a tiempo y mantener higiene diaria sin convertirla en un momento tenso.',
    category: 'salud',
    readTime: '4 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-02-28',
    updatedAt: '2026-03-02',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1200&q=80',
    tags: ['salud', 'higiene', 'prevencion'],
    heroNote: 'Cinco minutos de revision suave despues del paseo pueden prevenir irritaciones, infecciones y pequenas molestias acumuladas.',
    takeaways: [
      'Revisa almohadillas, orejas y pliegues con buena luz.',
      'No limpies en exceso si no hay suciedad visible ni indicacion veterinaria.',
      'Aprovecha este momento para detectar cambios de olor, color o sensibilidad.',
    ],
    ctaLabel: 'Leer mas sobre prevencion diaria',
    seoTitle: 'Cuidados de piel, orejas y patas despues del paseo | Vida Mascotera',
    seoDescription: 'Rutina breve y amable para revisar a tu mascota despues del paseo y detectar senales tempranas de incomodidad.',
    body: [
      {
        title: 'Las patas suelen contar la historia del paseo',
        paragraphs: [
          'Despues de caminar por tierra, pavimento o zonas humedas, conviene mirar las almohadillas y entre los dedos. Ahi suelen aparecer pequenas piedras, espigas o irritaciones.',
          'Una toalla suave y una revision rapida suelen ser suficientes para mantener limpieza sin resecar la piel.',
        ],
      },
      {
        title: 'Orejas y piel merecen una observacion tranquila',
        paragraphs: [
          'Mas que limpiar por rutina, la idea es observar. Un mal olor, enrojecimiento o sacudidas repetidas pueden ser senales de que algo necesita atencion.',
          'Lo mismo ocurre con la piel: tocar con suavidad permite notar zonas calientes, sensibles o mas asperas de lo normal.',
        ],
      },
      {
        title: 'Convierte el cuidado en una experiencia amable',
        paragraphs: [
          'Habla con voz tranquila, premia la colaboracion y evita forzar. Si este momento se vuelve desagradable, sera mas dificil repetirlo con constancia.',
          'La prevencion funciona mejor cuando forma parte de la rutina y no aparece solo cuando ya hay una molestia evidente.',
        ],
      },
    ],
  },
  {
    id: 'a5',
    slug: 'que-buscar-en-una-cama-premium-para-perro-o-gato',
    title: 'Que buscar en una cama premium para perro o gato',
    excerpt: 'Materiales, soporte y facilidad de limpieza para elegir una cama bonita, comoda y realmente durable.',
    category: 'accesorios',
    readTime: '5 min',
    author: 'Elena Prado',
    publishedAt: '2026-02-18',
    updatedAt: '2026-02-24',
    image: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&w=1200&q=80',
    tags: ['accesorios', 'compra', 'hogar'],
    heroNote: 'Una buena cama acompana descanso, regula temperatura y hace mas facil mantener el orden del hogar.',
    takeaways: [
      'Busca fundas lavables y materiales que mantengan forma con el uso.',
      'El tamano ideal permite estirarse sin perder sensacion de abrigo.',
      'El diseno importa, pero la comodidad real importa mas.',
    ],
    ctaLabel: 'Descubrir accesorios que si valen la pena',
    seoTitle: 'Como elegir una cama premium para tu mascota | Vida Mascotera',
    seoDescription: 'Consejos para comprar una cama comoda, resistente y facil de mantener para perros o gatos.',
    body: [
      {
        title: 'Soporte y tamano van primero',
        paragraphs: [
          'Una cama muy blanda puede deformarse rapido y una demasiado pequena termina usandose poco. Observa como duerme tu mascota y cuanto espacio necesita para estirarse o acurrucarse.',
          'Si tu perro o gato es senior, conviene priorizar soporte uniforme y acceso comodo antes que volumen visual.',
        ],
      },
      {
        title: 'La limpieza facil ahorra tiempo y evita frustraciones',
        paragraphs: [
          'Funda removible, tejidos que no atrapen demasiado pelo y materiales que se sequen bien despues del lavado ayudan a sostener la rutina sin esfuerzo extra.',
          'Una cama bonita que no puedes limpiar con facilidad termina durando menos y se vuelve una compra poco inteligente.',
        ],
      },
      {
        title: 'La estetica tambien puede jugar a favor',
        paragraphs: [
          'Cuando un accesorio se integra bien con tu casa, es mas probable que lo mantengas visible y disponible para tu mascota.',
          'El objetivo ideal es ese punto en el que diseno, descanso y practicidad conviven sin sacrificios innecesarios.',
        ],
      },
    ],
  },
  {
    id: 'a6',
    slug: 'transportadoras-blandas-vs-rigidas-cual-conviene',
    title: 'Transportadoras blandas vs rigidas: cual conviene mas',
    excerpt: 'Una comparativa clara para elegir segun trayectos, seguridad, ventilacion y tipo de uso cotidiano.',
    category: 'comparativas',
    readTime: '8 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-02-10',
    updatedAt: '2026-02-17',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1200&q=80',
    tags: ['comparativas', 'viaje', 'compra'],
    heroNote: 'La mejor transportadora no es la mas popular: es la que se adapta a tus trayectos y mantiene a tu mascota segura y calmada.',
    takeaways: [
      'Para uso urbano y trayectos cortos, las blandas suelen ser mas comodas de cargar.',
      'Para viajes largos o contextos mas exigentes, las rigidas suelen dar mas estructura.',
      'La ventilacion y la estabilidad pesan mas que el aspecto exterior.',
    ],
    ctaLabel: 'Ver productos para paseo y viaje',
    seoTitle: 'Transportadoras blandas vs rigidas: comparativa real | Vida Mascotera',
    seoDescription: 'Analizamos ventajas y limites de cada tipo de transportadora para ayudarte a comprar con criterio.',
    comparisonTable: {
      title: 'Comparativa rapida',
      optionALabel: 'Blanda',
      optionBLabel: 'Rigida',
      rows: [
        {
          criteria: 'Comodidad al cargar',
          optionA: 'Ligera y facil de guardar',
          optionB: 'Mas pesada y voluminosa',
          recommendation: 'La blanda gana en ciudad y trayectos cortos.',
        },
        {
          criteria: 'Estructura y proteccion',
          optionA: 'Depende del material y el uso',
          optionB: 'Mayor estabilidad general',
          recommendation: 'La rigida suele dar mas seguridad en traslados largos.',
        },
        {
          criteria: 'Limpieza',
          optionA: 'Puede requerir mas cuidado',
          optionB: 'Mas facil de desinfectar',
          recommendation: 'La rigida es mas practica si priorizas limpieza profunda.',
        },
      ],
    },
    body: [
      {
        title: 'La transportadora blanda funciona muy bien para lo cotidiano',
        paragraphs: [
          'Si haces trayectos cortos al veterinario, viajes urbanos o necesitas guardarla sin ocupar demasiado espacio, suele ser una gran aliada.',
          'Eso si, conviene elegir un modelo con base firme, ventilacion generosa y cierres resistentes para que la comodidad no comprometa seguridad.',
        ],
      },
      {
        title: 'La rigida suele transmitir mas estabilidad',
        paragraphs: [
          'Para desplazamientos mas largos, trayectos en auto o mascotas que necesitan una estructura mas definida, la version rigida suele resultar mas solida.',
          'Ademas, la limpieza profunda suele ser mas simple, algo especialmente util cuando hay mareos, suciedad o mayor frecuencia de uso.',
        ],
      },
      {
        title: 'La decision cambia segun tu rutina real',
        paragraphs: [
          'No elijas pensando en un escenario ideal, sino en lo que haras la mayor parte del tiempo. Una familia que viaja ocasionalmente no necesita lo mismo que alguien que se mueve varias veces por semana.',
          'Cuando la compra encaja con tu rutina, la transportadora deja de ser un objeto incomodo y se convierte en una herramienta util de cuidado.',
        ],
      },
    ],
  },
  {
    id: 'a7',
    slug: 'como-crear-una-rutina-de-paseo-mas-tranquila',
    title: 'Como crear una rutina de paseo mas tranquila para tu perro',
    excerpt: 'Cambios simples para que el paseo deje de sentirse caotico y se convierta en un momento de conexion.',
    category: 'perros',
    readTime: '6 min',
    author: 'Camila Nunez',
    publishedAt: '2026-02-06',
    updatedAt: '2026-02-12',
    image: 'https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=80',
    tags: ['paseo', 'rutinas', 'conducta'],
    heroNote: 'Un buen paseo no se mide por distancia, sino por calma, atencion y calidad de experiencia para ambos.',
    takeaways: [
      'Salir con menos prisa suele mejorar mucho el inicio del paseo.',
      'Pequenas pausas de olfato ayudan a bajar tension.',
      'La consistencia diaria vale mas que una salida perfecta de vez en cuando.',
    ],
    ctaLabel: 'Ver mas guias para paseo',
    seoTitle: 'Rutina de paseo mas tranquila para tu perro | Vida Mascotera',
    seoDescription: 'Consejos sencillos para mejorar la calidad del paseo diario y reducir tension en perros y tutores.',
    body: [
      {
        title: 'El paseo empieza antes de abrir la puerta',
        paragraphs: [
          'Si el arnes aparece siempre en medio de apuro o excitacion extrema, el perro aprende a salir con demasiada carga. Hablar bajo, preparar todo con tiempo y pedir una pausa corta cambia mucho el tono de la salida.',
          'No se trata de exigir inmovilidad perfecta. Basta con crear un inicio mas pausado y predecible.',
        ],
      },
      {
        title: 'Olfatear tambien es parte del paseo',
        paragraphs: [
          'Muchos perros descargan tension a traves del olfato. Dar espacio para explorar con calma suele mejorar la regulacion emocional y reducir tirones.',
          'Cuando el paseo solo consiste en avanzar, se pierde una parte importante del bienestar canino.',
        ],
      },
      {
        title: 'La rutina sostiene el progreso',
        paragraphs: [
          'Horarios parecidos, recorridos conocidos y expectativas realistas ayudan a que el paseo se vuelva mas facil con el tiempo.',
          'La mejora suele llegar por repeticion de buenos habitos, no por correcciones intensas.',
        ],
      },
    ],
  },
  {
    id: 'a8',
    slug: 'juegos-de-olfato-para-dias-de-lluvia',
    title: 'Juegos de olfato para dias de lluvia o poca energia',
    excerpt: 'Ideas sencillas para entretener a tu perro dentro de casa cuando salir no es una buena opcion.',
    category: 'perros',
    readTime: '4 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-01-29',
    updatedAt: '2026-02-01',
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1200&q=80',
    tags: ['juego', 'olfato', 'casa'],
    heroNote: 'No todos los dias necesitan una gran salida: a veces unos minutos de busqueda dentro de casa aportan justo lo que tu perro necesita.',
    takeaways: [
      'El olfato cansa de forma amable y util.',
      'Puedes empezar con premios faciles y aumentar dificultad poco a poco.',
      'Cinco o diez minutos bien guiados pueden marcar diferencia.',
    ],
    ctaLabel: 'Descubrir ideas indoor',
    seoTitle: 'Juegos de olfato en casa para perros | Vida Mascotera',
    seoDescription: 'Recursos simples para estimular a tu perro dentro de casa cuando no es posible salir como siempre.',
    body: [
      {
        title: 'Empieza con una dinamica muy simple',
        paragraphs: [
          'Esconde un premio a la vista, deja que lo encuentre y repite. Luego pasa a esconderlo detras de una silla, junto a una manta o debajo de una caja ligera.',
          'La idea es construir confianza antes de buscar mas dificultad.',
        ],
      },
      {
        title: 'Usa materiales que ya tienes',
        paragraphs: [
          'Toallas enrolladas, cajas de carton y recipientes livianos suelen ser suficientes para crear pequenos retos de busqueda.',
          'No hace falta comprar un juego especial para ofrecer una experiencia interesante.',
        ],
      },
      {
        title: 'Termina antes de que se canse demasiado',
        paragraphs: [
          'Un cierre amable deja buenas sensaciones y aumenta las ganas de repetir. Si esperas demasiado, puede pasar de estimulado a frustrado.',
          'La calidad del momento importa mas que la duracion.',
        ],
      },
    ],
  },
  {
    id: 'a9',
    slug: 'ventanas-seguras-y-rincones-de-sol-para-gatos',
    title: 'Ventanas seguras y rincones de sol para gatos',
    excerpt: 'Como crear un pequeno observatorio felino en casa sin comprometer seguridad ni orden visual.',
    category: 'gatos',
    readTime: '5 min',
    author: 'Lucia Ferrer',
    publishedAt: '2026-01-22',
    updatedAt: '2026-01-28',
    image: 'https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=1200&q=80',
    tags: ['ventanas', 'hogar', 'bienestar'],
    heroNote: 'Mirar hacia afuera, tomar sol y descansar en altura son pequeños lujos cotidianos que muchos gatos valoran profundamente.',
    takeaways: [
      'La seguridad de ventanas siempre va primero.',
      'Un solo punto de observacion bien resuelto puede ser suficiente.',
      'Sumar confort visual tambien mejora la experiencia del hogar humano.',
    ],
    ctaLabel: 'Ver mas ideas para gatos',
    seoTitle: 'Ventanas seguras y rincones de sol para gatos | Vida Mascotera',
    seoDescription: 'Aprende a crear un espacio de observacion seguro y agradable para gatos de interior.',
    body: [
      {
        title: 'Seguridad antes que estetica',
        paragraphs: [
          'Redes, mallas o soluciones firmes son imprescindibles si tu gato tendra acceso habitual a una ventana. No conviene improvisar cuando hay altura o aberturas amplias.',
          'Una base segura te permite luego pensar en comodidad y diseno.',
        ],
      },
      {
        title: 'El confort cambia la experiencia',
        paragraphs: [
          'Una mantita, un cojín plano o una repisa con textura amable convierten un borde de ventana en un rincón realmente habitable.',
          'Ese pequeño ajuste hace que el espacio se use mas y mejor.',
        ],
      },
      {
        title: 'Observacion y descanso pueden convivir',
        paragraphs: [
          'Muchos gatos alternan momentos de vigilancia suave con siestas cortas al sol. Diseñar ese punto para ambas cosas mejora su valor diario.',
          'No necesitas una gran instalacion para lograrlo.',
        ],
      },
    ],
  },
  {
    id: 'a10',
    slug: 'como-detectar-si-tu-gato-necesita-mas-estimulacion',
    title: 'Como detectar si tu gato necesita mas estimulacion',
    excerpt: 'Senales silenciosas que pueden indicar aburrimiento, exceso de energia o falta de variedad en casa.',
    category: 'gatos',
    readTime: '6 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-01-15',
    updatedAt: '2026-01-20',
    image: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?auto=format&fit=crop&w=1200&q=80',
    tags: ['juego', 'conducta', 'indoor'],
    heroNote: 'No siempre se trata de un problema de conducta: a veces tu gato solo necesita un entorno con mas oportunidades de explorar y jugar.',
    takeaways: [
      'La apatía y la inquietud pueden tener el mismo origen.',
      'Pequenos cambios de entorno pueden generar gran diferencia.',
      'La observacion diaria ayuda mas que una solucion impulsiva.',
    ],
    ctaLabel: 'Explorar guias felinas',
    seoTitle: 'Senales de que tu gato necesita mas estimulacion | Vida Mascotera',
    seoDescription: 'Claves para reconocer aburrimiento o falta de enriquecimiento en gatos de interior.',
    body: [
      {
        title: 'Algunas senales pasan desapercibidas',
        paragraphs: [
          'Dormir casi todo el dia, insistir con maullidos en ciertos horarios o buscar juego brusco de repente pueden ser formas de expresar falta de estimulo.',
          'Conviene mirar el conjunto de habitos y no una sola conducta aislada.',
        ],
      },
      {
        title: 'La variedad importa',
        paragraphs: [
          'Mover un rascador, cambiar un juguete o abrir una nueva ruta de altura puede renovar mucho el interes del gato por su entorno.',
          'No hace falta sumar cosas todo el tiempo, sino rotar mejor los recursos disponibles.',
        ],
      },
      {
        title: 'Una rutina de juego ayuda a ordenar el dia',
        paragraphs: [
          'Sesiones breves de juego antes de comer o al final de la tarde suelen dar estructura y descarga.',
          'Ese tipo de rituales mejora convivencia y bienestar con poco esfuerzo.',
        ],
      },
    ],
  },
  {
    id: 'a11',
    slug: 'como-leer-la-etiqueta-de-un-alimento-sin-volverte-loco',
    title: 'Como leer la etiqueta de un alimento sin volverte loco',
    excerpt: 'Una guia breve para entender ingredientes, orden de lista y mensajes de marketing con mas criterio.',
    category: 'alimentacion',
    readTime: '6 min',
    author: 'Dra. Paula Segura',
    publishedAt: '2026-01-10',
    updatedAt: '2026-01-14',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?auto=format&fit=crop&w=1200&q=80',
    tags: ['etiquetas', 'nutricion', 'compras'],
    heroNote: 'No necesitas memorizar toda una tabla tecnica para hacer una compra mas informada: basta con entender tres o cuatro puntos clave.',
    takeaways: [
      'La lista de ingredientes cuenta una parte importante de la historia.',
      'Promesas grandes en el frente del empaque no siempre significan mejor calidad.',
      'Comparar dos opciones con calma evita compras por impulso.',
    ],
    ctaLabel: 'Seguir aprendiendo sobre alimentacion',
    seoTitle: 'Como leer la etiqueta de un alimento para mascotas | Vida Mascotera',
    seoDescription: 'Claves para interpretar etiquetas de alimentos y comprar con mas criterio.',
    body: [
      {
        title: 'Empieza por lo mas visible',
        paragraphs: [
          'La lista de ingredientes y el analisis garantizado suelen ofrecer informacion suficiente para una comparacion basica entre opciones.',
          'No hace falta entrar en tecnicismos extremos para detectar diferencias claras.',
        ],
      },
      {
        title: 'No todo lo que suena premium lo es',
        paragraphs: [
          'Palabras como natural, balanceado o gourmet pueden ayudar a vender, pero no reemplazan una lectura minima del producto.',
          'Conviene mirar el conjunto y no dejarse guiar solo por el diseno del empaque.',
        ],
      },
      {
        title: 'Compara segun tu contexto',
        paragraphs: [
          'Edad, nivel de actividad, rutina de alimentacion y presupuesto cambian mucho la lectura correcta de una etiqueta.',
          'La mejor opcion es la que encaja con necesidades reales y se sostiene en el tiempo.',
        ],
      },
    ],
  },
  {
    id: 'a12',
    slug: 'senales-de-que-la-rutina-de-comida-necesita-ajustes',
    title: 'Senales de que la rutina de comida necesita ajustes',
    excerpt: 'Pequenos indicadores cotidianos para revisar horarios, porciones o formato antes de que aparezca el desorden.',
    category: 'alimentacion',
    readTime: '5 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-01-04',
    updatedAt: '2026-01-09',
    image: 'https://images.unsplash.com/photo-1583512603806-077998240c7a?auto=format&fit=crop&w=1200&q=80',
    tags: ['rutinas', 'porciones', 'bienestar'],
    heroNote: 'Muchas veces la alimentacion no necesita un gran cambio, sino pequeños ajustes de horario, ambiente o constancia.',
    takeaways: [
      'El contexto de la comida influye tanto como el alimento.',
      'Cambios de apetito merecen observacion, no solo reaccion inmediata.',
      'Una rutina clara da tranquilidad a toda la casa.',
    ],
    ctaLabel: 'Ver mas consejos de rutina',
    seoTitle: 'Cuando ajustar la rutina de comida de tu mascota | Vida Mascotera',
    seoDescription: 'Observa estas senales para revisar porciones, horarios o ambiente de alimentacion.',
    body: [
      {
        title: 'La velocidad tambien dice cosas',
        paragraphs: [
          'Comer con demasiada ansiedad, dejar siempre parte del plato o pedir comida fuera de horario pueden ser pistas de que algo necesita revisarse.',
          'No siempre es un problema del alimento en si.',
        ],
      },
      {
        title: 'El ambiente importa mas de lo que parece',
        paragraphs: [
          'Ruido, interrupciones, recipientes incomodos o cambios frecuentes de lugar pueden alterar una comida que en teoria estaba bien planteada.',
          'A veces mejorar el contexto resuelve mas que cambiar de marca.',
        ],
      },
      {
        title: 'Observa antes de decidir',
        paragraphs: [
          'Tomarte unos dias para mirar horarios, energia y respuesta digestiva da mejores pistas que una compra impulsiva.',
          'Los ajustes tranquilos suelen ser los mas sostenibles.',
        ],
      },
    ],
  },
  {
    id: 'a13',
    slug: 'botiquin-basico-para-el-dia-a-dia-con-mascotas',
    title: 'Botiquin basico para el dia a dia con mascotas',
    excerpt: 'Que si conviene tener a mano en casa y que es mejor dejar fuera para evitar errores innecesarios.',
    category: 'salud',
    readTime: '5 min',
    author: 'Dr. Marcelo Vidal',
    publishedAt: '2025-12-28',
    updatedAt: '2026-01-03',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1200&q=80',
    tags: ['hogar', 'prevencion', 'primeros-cuidados'],
    heroNote: 'Tener un pequeño botiquin no significa resolver todo en casa, sino estar mejor preparado para actuar con calma mientras pides ayuda si hace falta.',
    takeaways: [
      'Lo basico bien elegido suele ser suficiente.',
      'No automediques por intuicion.',
      'La informacion de tu veterinario siempre debe estar accesible.',
    ],
    ctaLabel: 'Leer mas sobre cuidados',
    seoTitle: 'Botiquin basico para mascotas en casa | Vida Mascotera',
    seoDescription: 'Una lista simple para organizar un botiquin domestico util y prudente para mascotas.',
    body: [
      {
        title: 'Piensa en orden y acceso rapido',
        paragraphs: [
          'Gasas, suero fisiologico, tijeras romas, guantes y numeros de contacto utiles son una base razonable para empezar.',
          'La organizacion importa tanto como el contenido.',
        ],
      },
      {
        title: 'Menos improvisacion, mejor criterio',
        paragraphs: [
          'Muchos productos humanos no deberian usarse sin indicacion profesional. Tenerlos a mano no significa que sean seguros para cualquier situacion.',
          'Conviene separar claramente lo apto para uso cotidiano de lo que requiere consulta.',
        ],
      },
      {
        title: 'Actualiza cada cierto tiempo',
        paragraphs: [
          'Revisar fechas, reponer faltantes y mantener una lista visible te ahorra dudas cuando aparece una urgencia menor.',
          'La prevencion tambien puede ser muy domestica.',
        ],
      },
    ],
  },
  {
    id: 'a14',
    slug: 'como-elegir-un-rascador-que-tu-gato-si-use',
    title: 'Como elegir un rascador que tu gato si use',
    excerpt: 'Altura, textura y ubicacion importan mucho mas que el tamano del accesorio o su precio.',
    category: 'accesorios',
    readTime: '5 min',
    author: 'Valeria Montes',
    publishedAt: '2025-12-22',
    updatedAt: '2025-12-27',
    image: 'https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=1200&q=80',
    tags: ['rascador', 'gatos', 'hogar'],
    heroNote: 'El mejor rascador no es el mas vistoso: es el que responde a como y donde le gusta rascar a tu gato.',
    takeaways: [
      'La estabilidad del rascador es clave.',
      'La ubicacion cambia por completo su uso.',
      'Conviene observar primero y comprar despues.',
    ],
    ctaLabel: 'Explorar accesorios felinos',
    seoTitle: 'Como elegir un rascador para gatos | Vida Mascotera',
    seoDescription: 'Consejos para comprar un rascador mas util, estable y atractivo para tu gato.',
    body: [
      {
        title: 'Mira que hace tu gato hoy',
        paragraphs: [
          'Si rasca superficies verticales, horizontales o esquinas, esa observacion ya te da una pista concreta sobre el formato mas adecuado.',
          'Comprar sin mirar esos habitos suele llevar a errores repetidos.',
        ],
      },
      {
        title: 'La textura y la firmeza importan',
        paragraphs: [
          'Muchos gatos rechazan rascadores que se mueven demasiado o se sienten blandos. La sensacion corporal influye mucho en la aceptacion.',
          'Una base firme transmite seguridad y favorece el uso espontaneo.',
        ],
      },
      {
        title: 'Ponlo donde ya vive el habito',
        paragraphs: [
          'Acercar el rascador a la zona donde ya rasca tu gato suele funcionar mejor que esconderlo para mantener la casa impecable.',
          'Primero conviene consolidar uso, luego afinar ubicacion.',
        ],
      },
    ],
  },
  {
    id: 'a15',
    slug: 'comedero-lento-vs-plato-amplio-que-ayuda-mas',
    title: 'Comedero lento vs plato amplio: que ayuda mas',
    excerpt: 'Una comparativa breve para elegir segun velocidad al comer, tipo de mascota y rutina de la casa.',
    category: 'comparativas',
    readTime: '7 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2025-12-16',
    updatedAt: '2025-12-21',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1200&q=80',
    tags: ['comparativas', 'alimentacion', 'accesorios'],
    heroNote: 'No todos los problemas al comer se resuelven con el mismo accesorio: el contexto y el tipo de mascota cambian mucho la respuesta.',
    takeaways: [
      'El comedero lento no siempre es la mejor solucion para todos.',
      'El plato amplio puede ayudar mas en ciertos gatos sensibles.',
      'Mirar la causa del problema evita compras innecesarias.',
    ],
    ctaLabel: 'Ver mas comparativas practicas',
    seoTitle: 'Comedero lento vs plato amplio | Vida Mascotera',
    seoDescription: 'Analisis simple para decidir entre comedero lento y plato amplio segun necesidad real.',
    comparisonTable: {
      title: 'Comparativa practica',
      optionALabel: 'Comedero lento',
      optionBLabel: 'Plato amplio',
      rows: [
        {
          criteria: 'Velocidad al comer',
          optionA: 'Ayuda a reducir ansiedad en algunos perros',
          optionB: 'No cambia mucho el ritmo',
          recommendation: 'Si el problema es comer demasiado rapido, el comedero lento suele ayudar mas.',
        },
        {
          criteria: 'Comodidad para bigotes',
          optionA: 'Puede resultar incomodo para ciertos gatos',
          optionB: 'Suele ser mas amable en gatos sensibles',
          recommendation: 'En felinos, el plato amplio gana cuando hay rechazo por contacto.',
        },
        {
          criteria: 'Limpieza',
          optionA: 'A veces requiere mas detalle',
          optionB: 'Suele ser mas simple de lavar',
          recommendation: 'El plato amplio facilita mantenimiento diario.',
        },
      ],
    },
    body: [
      {
        title: 'Primero identifica el problema real',
        paragraphs: [
          'No es lo mismo un perro que come con ansiedad que un gato que evita el plato por incomodidad o estres. Elegir bien empieza por observar mejor.',
          'Un accesorio correcto puede ayudar mucho, pero no reemplaza el diagnostico cotidiano.',
        ],
      },
      {
        title: 'Cada formato tiene su escenario',
        paragraphs: [
          'El comedero lento introduce obstaculos y reduce velocidad. El plato amplio da mas espacio y puede mejorar la experiencia de ciertos gatos o mascotas sensibles.',
          'No conviene esperar que ambos resuelvan lo mismo.',
        ],
      },
      {
        title: 'Lo practico tambien cuenta',
        paragraphs: [
          'Si el accesorio es incomodo de limpiar o termina guardado en un cajon, deja de ser una solucion real.',
          'La mejor compra es la que se sostiene en el uso diario.',
        ],
      },
    ],
  },
]

export const mockProducts: ProductRecommendation[] = [
  {
    id: 'p1',
    slug: 'arnes-ergonomico-de-paseo-diario',
    name: 'Arnes ergonomico de paseo diario',
    category: 'perros',
    description: 'Comodo, seguro y pensado para paseos que suman control sin restar libertad de movimiento.',
    longDescription:
      'Este arnes esta pensado para tutores que quieren un paseo mas comodo y seguro sin endurecer la experiencia del perro. Su ajuste reparte mejor la tension y facilita un uso cotidiano mas amable.',
    useCases: ['Paseos diarios', 'Perros activos', 'Aprendizaje de paseo con correa'],
    rating: 4.8,
    priceLabel: 'Gama media premium',
    affiliateHint: 'Ideal para perros activos y tutores que buscan un ajuste firme sin rigidez excesiva.',
    image: 'https://images.unsplash.com/photo-1598137261397-1f358d1f6b89?auto=format&fit=crop&w=1200&q=80',
    badge: 'Favorito para paseo',
    ctaLabel: 'Ver recomendacion',
    seoTitle: 'Arnes ergonomico de paseo diario | Vida Mascotera',
    seoDescription: 'Una recomendacion editorial para mejorar confort y control en paseos cotidianos con tu perro.',
  },
  {
    id: 'p2',
    slug: 'fuente-silenciosa-para-gatos',
    name: 'Fuente silenciosa para gatos',
    category: 'gatos',
    description: 'Favorece hidratacion diaria y se integra bien en hogares donde el ruido importa.',
    longDescription:
      'Una fuente silenciosa puede marcar diferencia en hogares con gatos de interior que necesitan un pequeno estimulo extra para beber agua. Aporta rutina, bienestar y una presencia visual amable.',
    useCases: ['Gatos de interior', 'Hidratacion diaria', 'Hogares con ruido sensible'],
    rating: 4.7,
    priceLabel: 'Seleccion recomendada',
    affiliateHint: 'Muy util para gatos de interior que necesitan un pequeno estimulo extra para beber agua.',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1200&q=80',
    badge: 'Bienestar diario',
    ctaLabel: 'Descubrir por que gusta',
    seoTitle: 'Fuente silenciosa para gatos | Vida Mascotera',
    seoDescription: 'Una recomendacion pensada para mejorar hidratacion, calma y rutina en gatos de interior.',
  },
  {
    id: 'p3',
    slug: 'comedero-elevado-de-ceramica',
    name: 'Comedero elevado de ceramica',
    category: 'alimentacion',
    description: 'Limpio, estable y facil de incorporar a una rutina de alimentacion mas ordenada.',
    longDescription:
      'Pensado para hogares que valoran funcionalidad e higiene, este comedero suma estabilidad y una presencia discreta en cocina o zona de alimentacion.',
    useCases: ['Rutinas ordenadas', 'Hogares pequenos', 'Alimentacion con foco en higiene'],
    rating: 4.6,
    priceLabel: 'Premium accesible',
    affiliateHint: 'Buena opcion para hogares que valoran funcionalidad, higiene y una estetica serena.',
    image: 'https://images.unsplash.com/photo-1583512603806-077998240c7a?auto=format&fit=crop&w=1200&q=80',
    badge: 'Compra inteligente',
    ctaLabel: 'Ver detalle editorial',
    seoTitle: 'Comedero elevado de ceramica | Vida Mascotera',
    seoDescription: 'Recomendacion editorial para una rutina de comida mas limpia, estable y agradable.',
  },
  {
    id: 'p4',
    slug: 'cama-envolvente-con-funda-lavable',
    name: 'Cama envolvente con funda lavable',
    category: 'accesorios',
    description: 'Aporta descanso real, se mantiene mejor con el tiempo y ayuda a que cada rincon se vea mas ordenado.',
    longDescription:
      'Una cama bien elegida mejora descanso, ayuda a organizar el hogar y acompana mejor las rutinas de siesta o noche. Esta opcion busca equilibrio entre comodidad, duracion y facil mantenimiento.',
    useCases: ['Descanso diario', 'Mascotas senior', 'Hogares que priorizan orden visual'],
    rating: 4.9,
    priceLabel: 'Descanso premium',
    affiliateHint: 'Especialmente util para mascotas que buscan apoyo y sensacion de refugio al dormir.',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
    badge: 'Muy recomendada',
    ctaLabel: 'Explorar ventajas',
    seoTitle: 'Cama envolvente con funda lavable | Vida Mascotera',
    seoDescription: 'Un accesorio pensado para mejorar descanso, confort y orden en casa.',
  },
]
