import type { Article, ProductRecommendation } from '@/types/content'

export const mockArticles: Article[] = [
  {
    id: 'a1',
    slug: 'checklist-realista-para-recibir-a-un-cachorro',
    title: 'Checklist realista para recibir a un cachorro en casa',
    excerpt: 'Lo esencial para preparar espacio, rutinas y primeras compras sin agobiarte ni gastar de mas.',
    category: 'perros',
    readTime: '6 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-03-12',
    updatedAt: '2026-03-18',
    featured: true,
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80',
    tags: ['cachorros', 'rutinas', 'hogar'],
    heroNote: 'Una llegada tranquila cambia por completo la adaptacion de tu cachorro durante las primeras semanas.',
    takeaways: [
      'Prioriza orden, descanso y horarios estables antes que comprar demasiadas cosas.',
      'Haz una primera visita veterinaria temprana para tener una hoja de ruta clara.',
      'Reduce estimulos y presenta cada espacio de la casa de forma progresiva.',
    ],
    ctaLabel: 'Ver esenciales para el dia a dia',
    seoTitle: 'Checklist para recibir a un cachorro en casa | Vida Mascotera',
    seoDescription: 'Guia practica para preparar tu hogar, definir rutinas y acompanar a tu cachorro con calma desde el primer dia.',
    body: [
      {
        title: 'Empieza por el ambiente, no por las compras',
        paragraphs: [
          'Un cachorro no necesita una casa perfecta, necesita un entorno predecible. Define una zona de descanso, un lugar fijo para comer y una rutina simple para sus primeros dias.',
          'Cuando todo cambia al mismo tiempo, la adaptacion se vuelve mas dificil. Menos ruido, menos visitas y mas calma suelen dar mejores resultados que una bienvenida llena de estimulos.',
        ],
      },
      {
        title: 'Crea una rutina amable desde el primer dia',
        paragraphs: [
          'Los horarios de comida, sueno, paseo y juego ayudan a que el cachorro entienda que esperar. Eso reduce ansiedad, accidentes en casa y despertares mas caoticos.',
          'No hace falta hacerlo perfecto. Lo importante es repetir una estructura simple para que poco a poco empiece a sentirse seguro.',
        ],
      },
      {
        title: 'Compra lo que vas a usar de verdad',
        paragraphs: [
          'Cama lavable, comedero facil de limpiar, arnes comodo, placas de identificacion y juguetes resistentes suelen ser una mejor inversion que accesorios improvisados.',
          'Antes de comprar por impulso, piensa si ese producto mejora bienestar, seguridad o convivencia diaria. Si no cumple una de esas tres funciones, puede esperar.',
        ],
      },
    ],
  },
  {
    id: 'a2',
    slug: 'como-enriquecer-un-departamento-para-un-gato-indoor',
    title: 'Como enriquecer un departamento para un gato indoor',
    excerpt: 'Ideas concretas para sumar altura, juego y descanso sin saturar el espacio ni romper la armonia de tu hogar.',
    category: 'gatos',
    readTime: '5 min',
    author: 'Marta Cifuentes',
    publishedAt: '2026-03-09',
    updatedAt: '2026-03-15',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=80',
    tags: ['indoor', 'hogar', 'bienestar'],
    heroNote: 'Un gato que puede observar, esconderse, rascar y jugar a diario suele vivir mas tranquilo y mas estimulado.',
    takeaways: [
      'La verticalidad importa tanto como el espacio horizontal.',
      'Es mejor tener pocos recursos bien ubicados que muchos elementos dispersos.',
      'El juego corto y frecuente suele funcionar mejor que una sesion larga ocasional.',
    ],
    ctaLabel: 'Explorar ideas para espacios felinos',
    seoTitle: 'Como enriquecer un departamento para un gato indoor | Vida Mascotera',
    seoDescription: 'Descubre como crear un espacio seguro, estimulante y armonioso para un gato de interior.',
    body: [
      {
        title: 'La altura es parte del bienestar felino',
        paragraphs: [
          'Los gatos de interior necesitan puntos altos para observar el entorno, descansar y sentirse seguros. Estantes, rascadores altos o muebles junto a una ventana pueden cambiar mucho su rutina.',
          'No se trata de llenar la casa de estructuras. Basta con crear uno o dos recorridos bien pensados que les permitan subir, parar y mirar con calma.',
        ],
      },
      {
        title: 'Escondites y zonas de descanso reducen el estres',
        paragraphs: [
          'Una caja, una cama tipo cueva o una manta en un rincon tranquilo pueden ser suficientes para que tu gato tenga un refugio propio.',
          'Cuando los gatos sienten que siempre tienen donde retirarse, suelen mostrarse mas confiados y mas abiertos al juego y al contacto.',
        ],
      },
      {
        title: 'Jugar tambien es una forma de cuidar',
        paragraphs: [
          'El juego estimula, previene aburrimiento y ayuda a canalizar energia. Varitas, pelotas ligeras y pequenos circuitos de busqueda suelen dar buen resultado.',
          'Reserva unos minutos dos o tres veces al dia. Esa frecuencia suele ser mas efectiva que esperar al fin de semana para compensar.',
        ],
      },
    ],
  },
  {
    id: 'a3',
    slug: 'pienso-humedo-o-mixto-como-elegir-segun-tu-mascota',
    title: 'Pienso, humedo o mixto: como elegir segun tu mascota',
    excerpt: 'Una guia sencilla para entender ventajas, limites y cuando conviene combinar formatos sin complicarte.',
    category: 'alimentacion',
    readTime: '7 min',
    author: 'Dra. Ana Reategui',
    publishedAt: '2026-03-04',
    updatedAt: '2026-03-10',
    image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?auto=format&fit=crop&w=1200&q=80',
    tags: ['nutricion', 'comparativa', 'guia'],
    heroNote: 'No existe un unico formato ideal para todos: la mejor eleccion depende de hidratacion, rutina, presupuesto y tolerancia digestiva.',
    takeaways: [
      'Observa energia, digestion, hidratacion y apetito, no solo el precio del alimento.',
      'El formato mixto puede ser util cuando quieres equilibrio entre practicidad y palatabilidad.',
      'Cualquier cambio debe hacerse de forma gradual durante varios dias.',
    ],
    ctaLabel: 'Ver seleccion para la hora de comer',
    seoTitle: 'Pienso, humedo o mixto: como elegir mejor | Vida Mascotera',
    seoDescription: 'Comparativa clara entre alimento seco, humedo y mixto para decidir segun las necesidades reales de tu mascota.',
    body: [
      {
        title: 'El alimento seco destaca por practicidad',
        paragraphs: [
          'Suele ser comodo de almacenar, facil de racionar y mas estable una vez abierto. Para muchas familias esto facilita mantener horarios regulares.',
          'Aun asi, conviene vigilar que tu mascota beba suficiente agua y revisar siempre la calidad de ingredientes y la tolerancia digestiva.',
        ],
      },
      {
        title: 'El formato humedo suma hidratacion y atractivo',
        paragraphs: [
          'Es una opcion interesante para mascotas con poco interes por el agua, etapas sensibles o apetito irregular.',
          'Como suele tener otra relacion costo-porcion, puede funcionar mejor como alimento principal en ciertos casos o como apoyo dentro de una pauta combinada.',
        ],
      },
      {
        title: 'El esquema mixto puede ser el punto medio',
        paragraphs: [
          'Combinar ambos formatos permite sumar hidratacion sin renunciar a la practicidad. Tambien ayuda a hacer las comidas mas variadas para algunos perros y gatos.',
          'La clave esta en mantener porciones claras y evitar improvisar cantidades, porque un sistema mixto mal ajustado puede llevar a excesos sin darte cuenta.',
        ],
      },
    ],
  },
  {
    id: 'a4',
    slug: 'cuidados-basicos-de-piel-oidos-y-patas-despues-del-paseo',
    title: 'Cuidados basicos de piel, oidos y patas despues del paseo',
    excerpt: 'Una rutina breve para detectar molestias a tiempo y mantener higiene diaria sin convertirla en un momento tenso.',
    category: 'salud',
    readTime: '4 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-02-28',
    updatedAt: '2026-03-02',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1200&q=80',
    tags: ['salud', 'higiene', 'prevencion'],
    heroNote: 'Cinco minutos de revision suave despues del paseo pueden prevenir irritaciones, infecciones y pequenas molestias acumuladas.',
    takeaways: [
      'Revisa almohadillas, orejas y pliegues con buena luz.',
      'No limpies en exceso si no hay suciedad visible ni indicacion veterinaria.',
      'Aprovecha este momento para detectar cambios de olor, color o sensibilidad.',
    ],
    ctaLabel: 'Leer mas sobre prevencion diaria',
    seoTitle: 'Cuidados de piel, orejas y patas despues del paseo | Vida Mascotera',
    seoDescription: 'Rutina breve y amable para revisar a tu mascota despues del paseo y detectar senales tempranas de incomodidad.',
    body: [
      {
        title: 'Las patas suelen contar la historia del paseo',
        paragraphs: [
          'Despues de caminar por tierra, pavimento o zonas humedas, conviene mirar las almohadillas y entre los dedos. Ahi suelen aparecer pequenas piedras, espigas o irritaciones.',
          'Una toalla suave y una revision rapida suelen ser suficientes para mantener limpieza sin resecar la piel.',
        ],
      },
      {
        title: 'Orejas y piel merecen una observacion tranquila',
        paragraphs: [
          'Mas que limpiar por rutina, la idea es observar. Un mal olor, enrojecimiento o sacudidas repetidas pueden ser senales de que algo necesita atencion.',
          'Lo mismo ocurre con la piel: tocar con suavidad permite notar zonas calientes, sensibles o mas asperas de lo normal.',
        ],
      },
      {
        title: 'Convierte el cuidado en una experiencia amable',
        paragraphs: [
          'Habla con voz tranquila, premia la colaboracion y evita forzar. Si este momento se vuelve desagradable, sera mas dificil repetirlo con constancia.',
          'La prevencion funciona mejor cuando forma parte de la rutina y no aparece solo cuando ya hay una molestia evidente.',
        ],
      },
    ],
  },
  {
    id: 'a5',
    slug: 'que-buscar-en-una-cama-premium-para-perro-o-gato',
    title: 'Que buscar en una cama premium para perro o gato',
    excerpt: 'Materiales, soporte y facilidad de limpieza para elegir una cama bonita, comoda y realmente durable.',
    category: 'accesorios',
    readTime: '5 min',
    author: 'Elena Prado',
    publishedAt: '2026-02-18',
    updatedAt: '2026-02-24',
    image: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&w=1200&q=80',
    tags: ['accesorios', 'compra', 'hogar'],
    heroNote: 'Una buena cama acompana descanso, regula temperatura y hace mas facil mantener el orden del hogar.',
    takeaways: [
      'Busca fundas lavables y materiales que mantengan forma con el uso.',
      'El tamano ideal permite estirarse sin perder sensacion de abrigo.',
      'El diseno importa, pero la comodidad real importa mas.',
    ],
    ctaLabel: 'Descubrir accesorios que si valen la pena',
    seoTitle: 'Como elegir una cama premium para tu mascota | Vida Mascotera',
    seoDescription: 'Consejos para comprar una cama comoda, resistente y facil de mantener para perros o gatos.',
    body: [
      {
        title: 'Soporte y tamano van primero',
        paragraphs: [
          'Una cama muy blanda puede deformarse rapido y una demasiado pequena termina usandose poco. Observa como duerme tu mascota y cuanto espacio necesita para estirarse o acurrucarse.',
          'Si tu perro o gato es senior, conviene priorizar soporte uniforme y acceso comodo antes que volumen visual.',
        ],
      },
      {
        title: 'La limpieza facil ahorra tiempo y evita frustraciones',
        paragraphs: [
          'Funda removible, tejidos que no atrapen demasiado pelo y materiales que se sequen bien despues del lavado ayudan a sostener la rutina sin esfuerzo extra.',
          'Una cama bonita que no puedes limpiar con facilidad termina durando menos y se vuelve una compra poco inteligente.',
        ],
      },
      {
        title: 'La estetica tambien puede jugar a favor',
        paragraphs: [
          'Cuando un accesorio se integra bien con tu casa, es mas probable que lo mantengas visible y disponible para tu mascota.',
          'El objetivo ideal es ese punto en el que diseno, descanso y practicidad conviven sin sacrificios innecesarios.',
        ],
      },
    ],
  },
  {
    id: 'a6',
    slug: 'transportadoras-blandas-vs-rigidas-cual-conviene',
    title: 'Transportadoras blandas vs rigidas: cual conviene mas',
    excerpt: 'Una comparativa clara para elegir segun trayectos, seguridad, ventilacion y tipo de uso cotidiano.',
    category: 'comparativas',
    readTime: '8 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-02-10',
    updatedAt: '2026-02-17',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1200&q=80',
    tags: ['comparativas', 'viaje', 'compra'],
    heroNote: 'La mejor transportadora no es la mas popular: es la que se adapta a tus trayectos y mantiene a tu mascota segura y calmada.',
    takeaways: [
      'Para uso urbano y trayectos cortos, las blandas suelen ser mas comodas de cargar.',
      'Para viajes largos o contextos mas exigentes, las rigidas suelen dar mas estructura.',
      'La ventilacion y la estabilidad pesan mas que el aspecto exterior.',
    ],
    ctaLabel: 'Ver productos para paseo y viaje',
    seoTitle: 'Transportadoras blandas vs rigidas: comparativa real | Vida Mascotera',
    seoDescription: 'Analizamos ventajas y limites de cada tipo de transportadora para ayudarte a comprar con criterio.',
    comparisonTable: {
      title: 'Comparativa rapida',
      optionALabel: 'Blanda',
      optionBLabel: 'Rigida',
      rows: [
        {
          criteria: 'Comodidad al cargar',
          optionA: 'Ligera y facil de guardar',
          optionB: 'Mas pesada y voluminosa',
          recommendation: 'La blanda gana en ciudad y trayectos cortos.',
        },
        {
          criteria: 'Estructura y proteccion',
          optionA: 'Depende del material y el uso',
          optionB: 'Mayor estabilidad general',
          recommendation: 'La rigida suele dar mas seguridad en traslados largos.',
        },
        {
          criteria: 'Limpieza',
          optionA: 'Puede requerir mas cuidado',
          optionB: 'Mas facil de desinfectar',
          recommendation: 'La rigida es mas practica si priorizas limpieza profunda.',
        },
      ],
    },
    body: [
      {
        title: 'La transportadora blanda funciona muy bien para lo cotidiano',
        paragraphs: [
          'Si haces trayectos cortos al veterinario, viajes urbanos o necesitas guardarla sin ocupar demasiado espacio, suele ser una gran aliada.',
          'Eso si, conviene elegir un modelo con base firme, ventilacion generosa y cierres resistentes para que la comodidad no comprometa seguridad.',
        ],
      },
      {
        title: 'La rigida suele transmitir mas estabilidad',
        paragraphs: [
          'Para desplazamientos mas largos, trayectos en auto o mascotas que necesitan una estructura mas definida, la version rigida suele resultar mas solida.',
          'Ademas, la limpieza profunda suele ser mas simple, algo especialmente util cuando hay mareos, suciedad o mayor frecuencia de uso.',
        ],
      },
      {
        title: 'La decision cambia segun tu rutina real',
        paragraphs: [
          'No elijas pensando en un escenario ideal, sino en lo que haras la mayor parte del tiempo. Una familia que viaja ocasionalmente no necesita lo mismo que alguien que se mueve varias veces por semana.',
          'Cuando la compra encaja con tu rutina, la transportadora deja de ser un objeto incomodo y se convierte en una herramienta util de cuidado.',
        ],
      },
    ],
  },
]

export const mockProducts: ProductRecommendation[] = [
  {
    id: 'p1',
    slug: 'arnes-ergonomico-de-paseo-diario',
    name: 'Arnes ergonomico de paseo diario',
    category: 'perros',
    description: 'Comodo, seguro y pensado para paseos que suman control sin restar libertad de movimiento.',
    longDescription:
      'Este arnes esta pensado para tutores que quieren un paseo mas comodo y seguro sin endurecer la experiencia del perro. Su ajuste reparte mejor la tension y facilita un uso cotidiano mas amable.',
    useCases: ['Paseos diarios', 'Perros activos', 'Aprendizaje de paseo con correa'],
    rating: 4.8,
    priceLabel: 'Gama media premium',
    affiliateHint: 'Ideal para perros activos y tutores que buscan un ajuste firme sin rigidez excesiva.',
    image: 'https://images.unsplash.com/photo-1598137261397-1f358d1f6b89?auto=format&fit=crop&w=1200&q=80',
    badge: 'Favorito para paseo',
    ctaLabel: 'Ver recomendacion',
    seoTitle: 'Arnes ergonomico de paseo diario | Vida Mascotera',
    seoDescription: 'Una recomendacion editorial para mejorar confort y control en paseos cotidianos con tu perro.',
  },
  {
    id: 'p2',
    slug: 'fuente-silenciosa-para-gatos',
    name: 'Fuente silenciosa para gatos',
    category: 'gatos',
    description: 'Favorece hidratacion diaria y se integra bien en hogares donde el ruido importa.',
    longDescription:
      'Una fuente silenciosa puede marcar diferencia en hogares con gatos de interior que necesitan un pequeno estimulo extra para beber agua. Aporta rutina, bienestar y una presencia visual amable.',
    useCases: ['Gatos de interior', 'Hidratacion diaria', 'Hogares con ruido sensible'],
    rating: 4.7,
    priceLabel: 'Seleccion recomendada',
    affiliateHint: 'Muy util para gatos de interior que necesitan un pequeno estimulo extra para beber agua.',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1200&q=80',
    badge: 'Bienestar diario',
    ctaLabel: 'Descubrir por que gusta',
    seoTitle: 'Fuente silenciosa para gatos | Vida Mascotera',
    seoDescription: 'Una recomendacion pensada para mejorar hidratacion, calma y rutina en gatos de interior.',
  },
  {
    id: 'p3',
    slug: 'comedero-elevado-de-ceramica',
    name: 'Comedero elevado de ceramica',
    category: 'alimentacion',
    description: 'Limpio, estable y facil de incorporar a una rutina de alimentacion mas ordenada.',
    longDescription:
      'Pensado para hogares que valoran funcionalidad e higiene, este comedero suma estabilidad y una presencia discreta en cocina o zona de alimentacion.',
    useCases: ['Rutinas ordenadas', 'Hogares pequenos', 'Alimentacion con foco en higiene'],
    rating: 4.6,
    priceLabel: 'Premium accesible',
    affiliateHint: 'Buena opcion para hogares que valoran funcionalidad, higiene y una estetica serena.',
    image: 'https://images.unsplash.com/photo-1583512603806-077998240c7a?auto=format&fit=crop&w=1200&q=80',
    badge: 'Compra inteligente',
    ctaLabel: 'Ver detalle editorial',
    seoTitle: 'Comedero elevado de ceramica | Vida Mascotera',
    seoDescription: 'Recomendacion editorial para una rutina de comida mas limpia, estable y agradable.',
  },
  {
    id: 'p4',
    slug: 'cama-envolvente-con-funda-lavable',
    name: 'Cama envolvente con funda lavable',
    category: 'accesorios',
    description: 'Aporta descanso real, se mantiene mejor con el tiempo y ayuda a que cada rincon se vea mas ordenado.',
    longDescription:
      'Una cama bien elegida mejora descanso, ayuda a organizar el hogar y acompana mejor las rutinas de siesta o noche. Esta opcion busca equilibrio entre comodidad, duracion y facil mantenimiento.',
    useCases: ['Descanso diario', 'Mascotas senior', 'Hogares que priorizan orden visual'],
    rating: 4.9,
    priceLabel: 'Descanso premium',
    affiliateHint: 'Especialmente util para mascotas que buscan apoyo y sensacion de refugio al dormir.',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80',
    badge: 'Muy recomendada',
    ctaLabel: 'Explorar ventajas',
    seoTitle: 'Cama envolvente con funda lavable | Vida Mascotera',
    seoDescription: 'Un accesorio pensado para mejorar descanso, confort y orden en casa.',
  },
]
