import type { Article, ProductRecommendation } from '@/types/content'

export const mockArticles: Article[] = [
  {
    id: 'a1',
    title: 'Checklist realista para recibir a un cachorro en casa',
    excerpt: 'Una guía clara para preparar espacio, rutina, alimentación y primeras visitas veterinarias.',
    category: 'perros',
    readTime: '6 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-03-12',
    featured: true,
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80',
    tags: ['cachorros', 'rutinas', 'hogar'],
  },
  {
    id: 'a2',
    title: 'Cómo enriquecer un departamento para un gato indoor',
    excerpt: 'Ideas simples para sumar altura, escondites, rascado y estimulación sensorial sin saturar el espacio.',
    category: 'gatos',
    readTime: '5 min',
    author: 'Marta Cifuentes',
    publishedAt: '2026-03-09',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=80',
    tags: ['indoor', 'hogar', 'bienestar'],
  },
  {
    id: 'a3',
    title: 'Pienso, húmedo o mixto: cómo decidir según tu mascota',
    excerpt: 'Comparativa editorial de formatos de alimentación con criterios prácticos y observables.',
    category: 'alimentacion',
    readTime: '7 min',
    author: 'Dr. Ana Reátegui',
    publishedAt: '2026-03-04',
    image: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?auto=format&fit=crop&w=1200&q=80',
    tags: ['nutricion', 'comparativa', 'guia'],
  },
  {
    id: 'a4',
    title: 'Cuidados básicos de piel, oídos y patas después del paseo',
    excerpt: 'Rutina breve para reducir irritaciones, detectar señales tempranas y mantener higiene diaria.',
    category: 'salud',
    readTime: '4 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-02-28',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1200&q=80',
    tags: ['salud', 'higiene', 'prevencion'],
  },
  {
    id: 'a5',
    title: 'Qué buscar en una cama premium para perro o gato',
    excerpt: 'Materiales, soporte, limpieza y durabilidad para comprar mejor y gastar una sola vez.',
    category: 'accesorios',
    readTime: '5 min',
    author: 'Elena Prado',
    publishedAt: '2026-02-18',
    image: 'https://images.unsplash.com/photo-1548681528-6a5c45b66b42?auto=format&fit=crop&w=1200&q=80',
    tags: ['accesorios', 'compra', 'hogar'],
  },
  {
    id: 'a6',
    title: 'Transportadoras blandas vs rígidas: comparación rápida',
    excerpt: 'Ventajas y límites reales para viaje urbano, auto, vet y salidas ocasionales.',
    category: 'comparativas',
    readTime: '8 min',
    author: 'Equipo Vida Mascotera',
    publishedAt: '2026-02-10',
    image: 'https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1200&q=80',
    tags: ['comparativas', 'viaje', 'compra'],
  },
]

export const mockProducts: ProductRecommendation[] = [
  {
    id: 'p1',
    name: 'Arnés ergonómico de paseo diario',
    category: 'perros',
    description: 'Ajuste cómodo, puntos de tensión reforzados y buena distribución de carga.',
    rating: 4.8,
    priceLabel: 'Gama media-premium',
    affiliateHint: 'Ideal para futuras integraciones de afiliación por categoría y talla.',
    image: 'https://images.unsplash.com/photo-1598137261397-1f358d1f6b89?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'p2',
    name: 'Fuente silenciosa para gatos',
    category: 'gatos',
    description: 'Favorece hidratación, reduce ruido y se integra bien en espacios interiores.',
    rating: 4.7,
    priceLabel: 'Selección recomendada',
    affiliateHint: 'Buen candidato para listas de esenciales felinos.',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'p3',
    name: 'Comedero elevado de cerámica',
    category: 'alimentacion',
    description: 'Estética limpia, fácil de lavar y útil para rutinas de alimentación ordenadas.',
    rating: 4.6,
    priceLabel: 'Premium accesible',
    affiliateHint: 'Encaja en editoriales de nutrición y organización del hogar.',
    image: 'https://images.unsplash.com/photo-1583512603806-077998240c7a?auto=format&fit=crop&w=1200&q=80',
  },
]
